config/routes.rb
Rails.application.routes.draw do
  get 'orange/index'

  get 'op/cap1'
  get 'orange/cap1'
  get 'onepiece/caps'
  get 'login/index'
  get 'generos/action'
  get 'generos/mecha'
  get 'generos/shonen'
  get 'generos/romance'
  get 'generos/tecnologia'
  get 'imagenes/index'
  get 'videos/index'
  get 'home/index'
  root 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/generos_controller.rb
class GenerosController < ApplicationController
  def action
  end

  def mecha
  end

  def shonen
  end

  def tecnologia
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/imagenes_controller.rb
class ImagenesController < ApplicationController
  def index
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
end

app/controllers/onepiece_controller.rb
class OnepieceController < ApplicationController
  def caps
  end
end

app/controllers/op_controller.rb
class OpController < ApplicationController
  def cap1
  end
end

app/controllers/orange_controller.rb
class OrangeController < ApplicationController
  def index
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
    def index
      
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/generos_helper.rb
module GenerosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/imagenes_helper.rb
module ImagenesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/onepiece_helper.rb
module OnepieceHelper
end

app/helpers/op_helper.rb
module OpHelper
end

app/helpers/orange_helper.rb
module OrangeHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/generos/action.html.erb
<h1>Animes de Acción</h1>

app/views/generos/mecha.html.erb
<h1>Animes sobre Mechas</h1>

app/views/generos/romance.html.erb
<ul>
     <h1>Animes de Romance</h1>
    <h2 >Orange</h2>
    <li class="inline" ><%=link_to  image_tag("romance.png", alt:"No se pudo mostrar la imagen", width: 200, height: 200),
    orange_index_path %>
    </li>
</ul>

app/views/generos/shonen.html.erb
<h1>Animes Shonen</h1>
<ul>
    <h2>One piece</h2>
    <li class="inline"><%=link_to image_tag("onepiece.jpg", alt:"No se puede mostrar la imagen.", width: 200, height:200),
    onepiece_caps_path
     %></li>
</ul>

app/views/generos/tecnologia.html.erb
<h1>Animes de Tecnología</h1>

app/views/home/index.html.erb
<h1 id="h1home">Anime de 2017 </h1>
<div class="estrenos">
    <img class="imgestrenos"src="https://3.bp.blogspot.com/-JS1YDXWTEs8/WHlA6qmuhdI/AAAAAAAAGLc/cOAAERB0gaUxRk-vjCybT4wJISxtv7gdwCLcB/s1600/%255BHorribleSubs%255D%2BYoujo%2BSenki%2B-%2B02%2B%255B480p%255D.mkv_snapshot_18.22_%255B2017.01.13_21.03.46%255D.jpg" alt="No se pudo mostrar la imagen">
    <img class="imgestrenos"src="https://pbs.twimg.com/media/CeYxqHlUMAARO6j.jpg" alt="No se pudo mostrar la imagen">
    <img class="imgestrenos"src="https://www.guiltybit.com/wp-content/uploads/2017/03/estrenos-anime-primavera-2017-759x500.jpg" alt="no se pudo mostrar la imagen"  >
    <img class="imgestrenos"src="https://dimensiondandy.files.wordpress.com/2017/01/vlcsnap-2017-01-06-22h58m59s527.png?w=656" alt="No se pudo mostra la imagen">
</div>

app/views/imagenes/index.html.erb
<h1>Wallpapers HD</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Anime | 2017</title>
   <link rel="icon" href="images/icono1.png">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body> 
    <header>
        <nav class="navi">
            <ul class="no-list">
                <li class="inline" id="logo"> <h1 class="no-margin">Anime</h1>            </li>
                <li class="inline pd">     <%= link_to "Inicio", root_path %>             </li>
                <li class="inline pd">     <%= link_to "Generos", videos_index_path  %>   </li>
                <li class="inline pd">     <%= link_to "Imagenes", imagenes_index_path %> </li>
                <li class="inline login">  <%= link_to "Login", login_index_path%>        </li>
                <li class="inline signup"> <%= link_to "Sign-Up", login_index_path%>      </li>
            </ul>
        </nav>
    </header>
<%= yield %>

<footer class="navi">
    <p>Anime, ImagenesHD</p>
</footer>
</body>
</html>

app/views/login/index.html.erb
<div class="logind">
    <h1 class="hlogin">Login</h1>
    <form class="center-md" action="index.html" method="post">
        <p><input type="text" name="user" placeholder="User Name"></p>
        <p><input type="text" name="pass" placeholder="Password"></p>
        <input type="submit" name="submit" value="Login">
    </form>
</div>

<h2 class="center-md">or</h2>
<h1 class="center-md">Registrer</h1>

<div class="registro">
    <form class="center-md" action="index.html" method="post">
        <p><input type="text" name="usern" placeholder="User Name"></p>
        <p><input type="text" name="passn" placeholder="Password"></p>
        <p><input type="text" name="passc" placeholder="Confirm Password"></p>
        <input type="submit" name="submit" value="Registrer">
    </form>
</div>

app/views/onepiece/caps.html.erb
<ul class="capitulos">
    <%for i in 1..100 %>
        <li class="inline pd"><%= link_to "Capitulo #{i}", op_cap1_path %></li>
    <% end %>
</ul>

app/views/op/cap1.html.erb
<h1>Capitulo 1 |Sub Español</h1>
<div align="center">
    <video controls >
        <source src="/assets/cap1.mp4" type="video/mp4">
    </video>
</div>

app/views/orange/cap1.html.erb
<div align="center">
    <video autoplay controls>
        <source src="/assets/orangecap1.mp4" type="video/mp4">
    </video>
</div>

app/views/orange/index.html.erb
<h1>Orange </h1>
<ul class="capitulos">
    <%for i in 1..12 %>
        <li class="inline pd"><%= link_to "Capitulo #{i}", orange_cap1_path %></li>
    <% end %>
</ul>

app/views/videos/index.html.erb
<div class="estrenos">
  <ul>

  <li class="lista-genero">
    <h2 class="hgeneros">Accion</h2>
    <%= link_to image_tag("action.png", alt: "No se pudo mostrar la imagen", width:300, height:300), generos_action_path %>
  </li>

  <li class="lista-genero">
    <h2 class="hgeneros">Mecha</h2>
    <%= link_to image_tag("mecha.jpg", alt: "No se pudo mostrar la imagen", width:300, height:300), generos_mecha_path %>
  </li>

  <li class="lista-genero">
    <h2 class="hgeneros">Shonen</h2>
    <%= link_to image_tag("shonen.jpg", alt: "No se pudo mostrar la imagen", width:300, height:300), generos_shonen_path %>
  </li>

  <li class="lista-genero">
    <h2 class="hgeneros">Tecnología</h2>
    <%= link_to image_tag("tecnologia.jpg", alt: "No se pudo mostrar la imagen", width:300, height:300), generos_tecnologia_path %>
  </li>

  <li class="lista-genero">
    <h2 class="hgeneros">Romance</h2>
    <%= link_to image_tag("romance.png", alt: "No se pudo mostrar la imagen", width:300, height:300), generos_romance_path %>
  </li>
  
  </ul>
</div>